// <auto-generated />
using System;
using BackEndFinal.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackEndFinal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251120043251_TaoBangLanDau")]
    partial class TaoBangLanDau
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackEndFinal.Model.KetQuaHocTap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DiemRenLuyen")
                        .HasColumnType("integer");

                    b.Property<double>("GPA")
                        .HasColumnType("double precision");

                    b.Property<string>("MaSV")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenHocKy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("XepLoaiHocBong")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MaSV");

                    b.ToTable("KetQuaHocTaps");
                });

            modelBuilder.Entity("BackEndFinal.Model.KyLuat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("MaSV")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayQuyetDinh")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MaSV");

                    b.ToTable("KyLuats");
                });

            modelBuilder.Entity("BackEndFinal.Model.SinhVien", b =>
                {
                    b.Property<string>("MaSV")
                        .HasColumnType("text");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lop")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaSV");

                    b.ToTable("SinhViens");
                });

            modelBuilder.Entity("BackEndFinal.Model.KetQuaHocTap", b =>
                {
                    b.HasOne("BackEndFinal.Model.SinhVien", "SinhVien")
                        .WithMany("KetQuaHocTaps")
                        .HasForeignKey("MaSV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("BackEndFinal.Model.KyLuat", b =>
                {
                    b.HasOne("BackEndFinal.Model.SinhVien", "SinhVien")
                        .WithMany("KyLuats")
                        .HasForeignKey("MaSV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("BackEndFinal.Model.SinhVien", b =>
                {
                    b.Navigation("KetQuaHocTaps");

                    b.Navigation("KyLuats");
                });
#pragma warning restore 612, 618
        }
    }
}
